[project]
name = "bad-apple"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "natsort>=8.4.0",
    "numpy>=2.2.5",
    "pillow>=11.2.1",
    "srt>=3.5.3",
    "timecode>=1.4.1",
]
